<a href="https://colab.research.google.com/github/ilona1234/first/blob/master/cd_podstaw_pythona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [3]:
a_list+b_list
n_array+n_array

array([ 2,  4,  6,  8, 10])

In [4]:
a_list[3]

4

In [ ]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100, 100]


In [ ]:
k_krotka[4]

5

In [ ]:
k_krotka.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [5]:
n_array = np.array(a_list) # wektor numpy

In [ ]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat'], dtype=object)

In [ ]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [ ]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [ ]:
studenci_slownik["Zosia"]

22

In [ ]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [ ]:
for elementy in studenci_slownik.items():
    print(elementy)

('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])


In [ ]:
for elementy in studenci_slownik.values():
    print(elementy)

3
5
22
[2, 21]


In [ ]:
studenci_slownik["Cuthulu"]= -1000000

In [ ]:
studenci_slownik

{'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], 'Cuthulu': -1000000}

In [ ]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [ ]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 'Igor', 1: 'Frankek', 2: 'Zosia', 3: 'Julia', 4: 'Cuthulu'}


In [ ]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [ ]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [ ]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [ ]:
1 in a
"Igor" in studenci_slownik

True

### Własne typy

In [ ]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [ ]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [ ]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [ ]:
pio_zajecia.ile_zajec

4

In [ ]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [ ]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [ ]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia.ile_mispow()

4

In [ ]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [ ]:
print(pio_zajecia.ile_zajec)

5


In [ ]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [ ]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [ ]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

In [64]:
# ma na takie rzeczy być w stanie odpowiedzieć

# numer_lodz = NumerTelefonu("426877868")
# >>> "prawidlowy numer"

# numer_lodz.wojewodztwo 
#>>> "Lodz"


#print(numer_lodz)
#>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"


class NumerTelefonu():
  prefix_numerow_ruchomych=[50, 51, 53, 57, 60, 66, 69, 72, 73, 78, 79, 88]
  prefix_numerow_stacjonarnych=[12, 13, 14, 15, 16, 17, 18, 22, 23, 24, 25, 29, 32, 33, 34, 41, 42, 43, 44, 46, 48, 52, 54, 55, 56, 58, 59, 61, 62, 63, 65, 67, 68,
   71, 74, 75, 76, 77, 81, 82, 83, 84, 85, 86, 87, 89, 91, 94, 95]
  flaga = 0

  def __init__(self, numer_telefonu):
    self.numer_telefonu = numer_telefonu
    if len(numer_telefonu) == 9:
      for prefix in NumerTelefonu.prefix_numerow_stacjonarnych  + NumerTelefonu.prefix_numerow_ruchomych:
        if numer_telefonu[0:2] == str(prefix):
          print("prawidlowy numer")
          NumerTelefonu.flaga = 1
          break
      if NumerTelefonu.flaga == 0:
        print("błędny numer")
    else:
        print("błędny numer")

  @property
  def wojewodztwo(self):
    prefix_wojewodztw = {12: "Kraków", 13: "Krosno", 14: "Tarnów", 15: "Tarnobrzeg", 16: "Przemyśl", 17: "Rzeszów", 18: "Nowy Sącz", 22: "Warszawa", 23: "Ciechanów", 24: "Płock", 25: "Siedlce", 29: "Ostrołęka", 32: "Katowice", 33: "Bielsko-Biała", 34: "Częstochowa", 41: "Kielce", 42: "Łódź", 43: "Sieradz", 44: "Piotrków Tybunalski", 46: "Skierniewice", 48: "Radom", 52: "Bydgoszcz", 54: "Włocławek", 55: "Elbląg", 56: "Toruń", 58: "Gdańsk", 59: "Słupsk", 61: "Poznań", 62: "Kalisz", 63: "Konin", 65: "Leszno", 67: "Piła", 68: "Zielona Góra", 71: "Wrocław", 74: "Wałbrzych", 75: "Jelenia Góra", 76: "Legnica", 77: "Opole", 81: "Lublin", 82: "Chełm", 83: "Bielsko-Biała", 84: "Zamość", 85: "Białystok", 86: "Łomża", 87: "Suwałki", 89: "Olsztyn", 91: "Szczecin", 94: "Koszalin", 95: "Gorzów Wielkopolski"}
    for prefix in prefix_wojewodztw.items():
      if self.numer_telefonu[0:2] == str(prefix[0]):
        print(prefix[1])

  def __repr__(self):
    liczba = ""
    liczby = {0: "zero", 1: "jeden", 2: "dwa", 3: "trzy", 4: "cztery", 5: "pięć", 6: "sześć", 7: "siedem", 8: "osiem", 9: "dziewięć"}
    for cyfra in self.numer_telefonu:
      liczba += liczby[int(cyfra)] + " "
    return liczba
      
numer_lodz = NumerTelefonu("426877868")

numer_lodz.wojewodztwo

print(numer_lodz)



prawidlowy numer
Łódź
cztery dwa sześć osiem siedem siedem osiem sześć osiem 
